# Site settings
title: Brendan Asselstine
email: mail.asselstine@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm a full-stack web developer based in Vancouver, BC.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://brendanasselstine.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  asselstine

# Build settings
markdown: kramdown
